"""create_population_table

Revision ID: 965935d21bcd
Revises: 
Create Date: 2023-03-25 00:36:10.822607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '965935d21bcd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('population',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country', sa.String(length=250), nullable=False),
    sa.Column('numbers', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('population')
    # ### end Alembic commands ###
